
        package com.github.dapeng.hello.scala.service

        import com.github.dapeng.core.{Processor, Service}
        import com.github.dapeng.core.SoaGlobalTransactional
        import scala.concurrent.Future

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 

 Hello Service

        **/
        @Service(name ="com.github.dapeng.hello.service.HelloService" , version = "1.0.0")
        @Processor(className = "com.github.dapeng.hello.scala.HelloServiceAsyncCodec\$Processor")
        trait HelloServiceAsync {
        
            /**
            * 
            **/
            
            @throws[com.github.dapeng.core.SoaException]
            def sayHello(
            hello: com.github.dapeng.hello.scala.domain.Hello , timeout : Long): Future[String]
      }
      