package com.github.dapeng.hello;

      import com.github.dapeng.core.*;
      import com.github.dapeng.org.apache.thrift.*;
      import java.util.concurrent.CompletableFuture;
      import java.util.concurrent.Future;
      import java.util.ServiceLoader;
      import com.github.dapeng.hello.HelloServiceCodec.*;
      import com.github.dapeng.hello.service.HelloServiceAsync;

      /**
       * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

      **/
      public class HelloServiceAsyncClient implements HelloServiceAsync{
      private final String serviceName;
      private final String version;

      private SoaConnectionPool pool;

      public HelloServiceAsyncClient() {
        this.serviceName = "com.github.dapeng.hello.service.HelloService";
        this.version = "1.0.0";

        ServiceLoader<SoaConnectionPoolFactory> factories = ServiceLoader.load(SoaConnectionPoolFactory.class);
        for (SoaConnectionPoolFactory factory: factories) {
          this.pool = factory.getPool();
          break;
        }
        this.pool.registerClientInfo(serviceName,version);
      }

      
          
            /**
            * 
            **/
            
              public CompletableFuture<String> sayHello(com.github.dapeng.hello.domain.Hello hello, long timeout) throws SoaException{

              String methodName = "sayHello";
              sayHello_args sayHello_args = new sayHello_args();
              sayHello_args.setHello(hello);
                

              CompletableFuture<sayHello_result> response = (CompletableFuture<sayHello_result>) pool.sendAsync(serviceName,version,"sayHello",sayHello_args, new SayHello_argsSerializer(), new SayHello_resultSerializer(),timeout);

              
                  
                      return response.thenApply((sayHello_result result )->  result.getSuccess());
                    
                
            }

      /**
      * getServiceMetadata
      **/
      public String getServiceMetadata() throws SoaException {
        String methodName = "getServiceMetadata";
        getServiceMetadata_args getServiceMetadata_args = new getServiceMetadata_args();
        getServiceMetadata_result response = pool.send(serviceName,version,methodName,getServiceMetadata_args, new GetServiceMetadata_argsSerializer(), new GetServiceMetadata_resultSerializer());
        return response.getSuccess();
      }

    }
    