
        package com.github.dapeng.soa.hello.scala.service

        import com.github.dapeng.core.{Processor, Service}
        import com.github.dapeng.core.SoaGlobalTransactional

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 

 Hello Service

        **/
        @Service(name ="com.github.dapeng.soa.hello.service.HelloService" , version = "1.0.0")
        @Processor(className = "com.github.dapeng.soa.hello.scala.HelloServiceCodec\$Processor")
        trait HelloService {
        
            /**
            * 
            **/
            
            @throws[com.github.dapeng.core.SoaException]
            def sayHello(
            hello: com.github.dapeng.soa.hello.scala.domain.Hello ): String
          
        }
        